{
 "title": "AWS/CDN",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ID", "label": "ID", "query": "label_values(distribution_id)" }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_cloudfront_requests_sum{distribution_id=~\"$ID\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{distribution_id}}"
    }
   ]
  },
  {
   "title": "TotalError",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_cloudfront_total_error_rate_average{distribution_id=~\"$ID\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{distribution_id}}"
    }
   ]
  },
  {
   "title": "4xxError",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_cloudfront_4xx_error_rate_average{distribution_id=~\"$ID\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{distribution_id}}"
    }
   ]
  },
  {
   "title": "5xxError",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "aws_cloudfront_5xx_error_rate_average{distribution_id=~\"$ID\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{distribution_id}}"
    }
   ]
  }
 ]
}