{
 "title": "AWS/RDS",
 "description": "AWS RDS Dashboard",
 "tags": [ "rds" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instanceId",
    "label": "实例",
    "query": "label_values(dbinstance_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "数据库连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_sum{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "可用内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "可用存储空间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "写入IOPS(次数/秒)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_write_iops_average{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "读取IOPS(次数/秒)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "写入吞吐量(MB/秒)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_write_throughput_average{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "读取吞吐量(MB/秒)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_throughput_average{dbinstance_identifier=~\"$instanceId\",app=~\"prometheus-cloudwatch-exporter\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  }
 ]
}