{
 "title": "AWS/Redis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "Redis实例", "query": "label_values(cache_cluster_id)" }
  ]
 },
 "panels": [
  {
   "title": "当前连接",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elasticache_curr_connections_average {app=~\"prometheus-cloudwatch-exporter\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "剩余内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elasticache_freeable_memory_average {app=~\"prometheus-cloudwatch-exporter\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elasticache_cpuutilization_average {app=~\"prometheus-cloudwatch-exporter\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "网络流入",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elasticache_network_bytes_in_average {app=~\"prometheus-cloudwatch-exporter\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "网络流出",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elasticache_network_bytes_out_average {app=~\"prometheus-cloudwatch-exporter\"}) by (cache_cluster_id)",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  }
 ]
}