{
 "title": "AWS/ELB",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "ELB名称",
    "query": "label_values(load_balancer_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "请求数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elb_request_count_sum {app=~\"prometheus-cloudwatch-exporter\"}) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "ELB 4|5XX数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elb_httpcode_elb_5_xx_sum {app=~\"prometheus-cloudwatch-exporter\"} ) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    },
    {
     "expr": "sum (aws_elb_httpcode_elb_4_xx_sum {app=~\"prometheus-cloudwatch-exporter\"} ) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "后端连接错误",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elb_un_healthy_host_count_average {app=~\"prometheus-cloudwatch-exporter\"} ) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "HTTP 5|4XX数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elb_httpcode_backend_5_xx_sum {app=~\"prometheus-cloudwatch-exporter\"} ) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "溢出计数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elb_latency_average {app=~\"prometheus-cloudwatch-exporter\"}) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "队列长度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elb_surge_queue_length_maximum {app=~\"prometheus-cloudwatch-exporter\"}) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "不正常的主机数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (aws_elb_un_healthy_host_count_average {app=~\"prometheus-cloudwatch-exporter\"} ) by (load_balancer_name)",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  }
 ]
}